### ISSUE TITLE
Explicitly differentiate dbt unit tests from dbt data tests

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/data-architecture#382] opened 2024-04-16 21:45 UTC
dbt will soon include [unit tests](https://docs.getdbt.com/docs/build/unit-tests) for complex SQL logic and queries. We should absolutely use these and should also attempt to differentiate tests on raw data (`test_qc_` tests) from tests related to logic (tests for joins). We could do this via tagging.

We should also revisit our testing docs to clarify the ways our unit tests are written and run once we have a better idea of what they'll look like. See this comment for some ideas: https://github.com/ccao-data/data-architecture/pull/432#discussion_r1592724380

**Comment by jeancochrane** [comment] 2024-04-16 21:48
Note that we will also need to wait for dbt-athena to cut a release that supports dbt 1.8 before we can use unit tests. Luckily it seems like [they plan to do this immediately](https://github.com/dbt-athena/dbt-athena/issues/610), and the release is currently targeted for May 9.

**Comment by jeancochrane** [comment] 2024-05-21 19:29
Our old friend https://github.com/ccao-data/data-architecture/issues/238 bites us again: Unit tests use CTEs to template their fixtures into the compiled test query, meaning that until models with dots in their names are supported by dbt Core, we can't unit test any model that references another model ☹️ 

@dfsnow Do you think this is enough of a motivation to boost the priority of https://github.com/ccao-data/data-architecture/issues/238, or should we backburner unit tests for now?

**Comment by dfsnow** [comment] 2024-05-21 22:36
> Our old friend #238 bites us again: Unit tests use CTEs to template their fixtures into the compiled test query, meaning that until models with dots in their names are supported by dbt Core, we can't unit test any model that references another model ☹️
> 
> @dfsnow Do you think this is enough of a motivation to boost the priority of #238, or should we backburner unit tests for now?

Oof. The main problem here is that you can't have periods in CTE names right? That seems more like an Athena/`dbt-athena` problem to me. Perhaps there's a way to fix `dbt-athena` such that ephemeral models with dots are renamed.

Either way, let's check-in and see what else is on the list of upcoming stuff before we decide on priority.

**Comment by jeancochrane** [comment] 2024-06-07 22:10
Leaving a status update for the end of the week: I've got branches up for `dbt-core` and `dbt-adapters` that will fix the ephemeral model issue. (I also have the [`test-dbt-ephemeral-model-fix` branch](https://github.com/ccao-data/data-architecture/tree/jeancochrane/test-dbt-ephemeral-model-fix) up to test these changes in this repo.) Next step is putting up the core/adapter PRs and then requesting review from core maintainers.

In the process of testing that fix, I discovered that there's another blocker preventing us from moving forward with unit tests: The `dbt-athena` adapter doesn't properly return array column definitions when populating test fixtures, causing the following error:

```
TYPE_MISMATCH: line 502:9: Unknown type: array(string).
``` 

The root cause here is that [`get_columns_in_relation`](https://github.com/dbt-athena/dbt-athena/blob/aaca39795f564dfe4d641b33cfe39790aaf38f20/dbt/adapters/athena/impl.py#L1101) uses [`AthenaColumn`](https://github.com/dbt-athena/dbt-athena/blob/aaca39795f564dfe4d641b33cfe39790aaf38f20/dbt/adapters/athena/column.py#L11) to parse column definitions, which is necessary due to Athena's difference between DDL and DML syntaxes ([more details here](https://docs.aws.amazon.com/athena/latest/ug/data-types.html)) but `AthenaColumn` isn't yet configured to parse array types. See the [`ddl_data_type` macro](https://github.com/dbt-athena/dbt-athena/blob/aaca39795f564dfe4d641b33cfe39790aaf38f20/dbt/include/athena/macros/utils/ddl_dml_data_type.sql#L9) for an example of another function that handles this difference well.

Note that I'm also not sure why array types were being parsed in the particular case of the `default_vw_pin_universe_class_no_special_chars` test I was running; it's possible there's another bug causing incorrect array types to be set in certain cases, which may also need to be fixed. More investigation to come.

**Comment by jeancochrane** [comment] 2024-08-30 16:11
My bug fixes have officially been released as of [v1.8.6](https://github.com/dbt-labs/dbt-core/releases/tag/v1.8.6), so this should be unblocked!

**Closed** 2024-11-15 20:37 UTC
Labels: dbt
